// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertTxtToEpub(arg1:main.ConvertTxtParams):Promise<main.ConvertResult>;

export function GalleryCancelCrawl():Promise<void>;

export function GalleryCrawlAndPack(arg1:Array<main.Gallery>,arg2:string):Promise<main.CrawlResult>;

export function GallerySearch(arg1:string,arg2:number):Promise<main.GallerySearchResult>;

export function GallerySearchAll(arg1:string,arg2:number):Promise<main.GallerySearchResult>;

export function GallerySelectOutputFolder():Promise<string>;

export function GetPlatform():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function PreviewTxtChapters(arg1:main.PreviewTxtParams):Promise<main.PreviewResult>;

export function Scan7zFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ScanImageFolders(arg1:string):Promise<Array<main.FolderInfo>>;

export function ScanTxtFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ScanVideos(arg1:string):Promise<Array<main.VideoFile>>;

export function SelectSourceFolder():Promise<string>;

export function SelectTargetFolder():Promise<string>;

export function SelectTxtFile():Promise<main.FileInfo>;

export function TaskQueueAdd(arg1:string,arg2:any,arg3:string):Promise<number>;

export function TaskQueueCancel(arg1:number):Promise<void>;

export function TaskQueueClearCompleted():Promise<void>;

export function TaskQueueGetAll():Promise<Array<main.Task>>;
