// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertTxtToEpub(arg1) {
  return window['go']['main']['App']['ConvertTxtToEpub'](arg1);
}

export function GalleryCancelCrawl() {
  return window['go']['main']['App']['GalleryCancelCrawl']();
}

export function GalleryCrawlAndPack(arg1, arg2) {
  return window['go']['main']['App']['GalleryCrawlAndPack'](arg1, arg2);
}

export function GallerySearch(arg1, arg2) {
  return window['go']['main']['App']['GallerySearch'](arg1, arg2);
}

export function GallerySearchAll(arg1, arg2) {
  return window['go']['main']['App']['GallerySearchAll'](arg1, arg2);
}

export function GallerySelectOutputFolder() {
  return window['go']['main']['App']['GallerySelectOutputFolder']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PreviewTxtChapters(arg1) {
  return window['go']['main']['App']['PreviewTxtChapters'](arg1);
}

export function Scan7zFiles(arg1) {
  return window['go']['main']['App']['Scan7zFiles'](arg1);
}

export function ScanImageFolders(arg1) {
  return window['go']['main']['App']['ScanImageFolders'](arg1);
}

export function ScanTxtFiles(arg1) {
  return window['go']['main']['App']['ScanTxtFiles'](arg1);
}

export function ScanVideos(arg1) {
  return window['go']['main']['App']['ScanVideos'](arg1);
}

export function SelectSourceFolder() {
  return window['go']['main']['App']['SelectSourceFolder']();
}

export function SelectTargetFolder() {
  return window['go']['main']['App']['SelectTargetFolder']();
}

export function SelectTxtFile() {
  return window['go']['main']['App']['SelectTxtFile']();
}

export function TaskQueueAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskQueueAdd'](arg1, arg2, arg3);
}

export function TaskQueueCancel(arg1) {
  return window['go']['main']['App']['TaskQueueCancel'](arg1);
}

export function TaskQueueClearCompleted() {
  return window['go']['main']['App']['TaskQueueClearCompleted']();
}

export function TaskQueueGetAll() {
  return window['go']['main']['App']['TaskQueueGetAll']();
}
